name: Build MoonClient2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Java 8 and Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew build --stacktrace

      - name: Archive built mod jar
        uses: actions/upload-artifact@v3
        with:
          name: MoonClient2
          path: build/libs/*.jar
